### ISSUE TITLE
Astronomic Clock in rules

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/perseo-core#130]
It's mandatory to allow the usage of astronomic clock concepts in Perseo time rules. Mainly Sunset and Sunrise based on LAT/LOG values.

I suppose this could be achieved by adding the proper Java Library to Esper deployment.

**Comment by AlvaroVega** [comment]
Possible library to include: https://github.com/caarmen/SunriseSunset
How to include it in Esper: https://esper.espertech.com/release-6.1.0/esper-reference/html/configuration.html#config-class--package-imports

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-core/pull/132
