### ISSUE TITLE
Migrate to esper 8.X.0

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-core#136]

**Comment by fgalan** [comment]
According to https://mvnrepository.com/artifact/com.espertech/esper-runtime/8.3.0 it seems it is already in maven repositories...

**Comment by AlvaroVega** [comment]
But not in this: https://repo1.maven.org/maven2/com/espertech/esper/

**Comment by AlvaroVega** [comment]
According to http://www.espertech.com/esper/esper-changehistory/
Since version 8.0.0:

```There are significant API changes. Esper version 8 is not a drop-in replacement for Esper-7 and earlier.```

**Comment by fgalan** [comment]
Done in PR #176
