### ISSUE TITLE
log into stdout

### ISSUE THREAD

**Issue by IvanHdzC** [telefonicaid/perseo-core#163]
Currently perseo core logs into a file which outputs through a tail. It should log directly to stdout.

**Comment by AlvaroVega** [comment]
maybe is just tune configuration in log4jxml

**Comment by fgalan** [comment]
We have a somehow old security warning about log4j in this repository (https://github.com/telefonicaid/perseo-core/network/alerts). Maybe we could take the opportunity of this issue to fix also that.

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/perseo-core/pull/164
