### ISSUE TITLE
Support fort NGSI-LD

### ISSUE THREAD

**Issue by 181502** [telefonicaid/perseo-core#175]
Hi,

we would like to use perseo in conjunction with orion-ld. However, perseo only supports ngsi-v2. When is NGSI-LD support planned?

regards,
rob

**Comment by fgalan** [comment]
Perseo Core doesn't expose any NGSI API. It's a component that interacts only with Perse FE.

There is a similar issue in Perse FE repository: https://github.com/telefonicaid/perseo-fe/issues/547. That's the right one.
