### ISSUE TITLE
docker env var to set log level

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-core#178]
Currently there is no way to change log level without use API.
Currently default log level is INFO
A docker en var to set a a different log level would be desirable.

**Comment by AlvaroVega** [comment]
root@iot-perseo-core:/usr/local/tomcat/conf# grep INFO *
grep: Catalina: Is a directory
logging.properties:org.apache.catalina.core.ContainerBase.[Catalina].[localhost].level = INFO
logging.properties:org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/manager].level = INFO
logging.properties:org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/host-manager].level = INFO

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-core/pull/213
