### ISSUE TITLE
When the json sent to Perseo is too long, the parsing fails

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/perseo-core#6]
When the json sent to CEP is too long, the perseo-core fails parsing the json

```
{"error":"error post to http://10.95.82.36:8080/perseo-core/rules (Unterminated string at 2897 [character 2898 line 1])","data":null}
```

In addition to a fix in the code to check JSON length and report an error, the "too long" should defined (and documented) as part of the resolution of this bug.

**Comment by fgalan** [comment]
Fixed in PR #7

**Comment by fgalan** [comment]
To be closed when jenkins tell us that everything is ok :)

**Comment by jcalderin** [comment]
Jenkins has spoken, :)
